//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "bundle")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::seasons::Entity")]
    Seasons,
}

impl Related<super::seasons::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Seasons.def()
    }
}

impl Related<super::fishes::Entity> for Entity {
    fn to() -> RelationDef {
        super::fish_bundle::Relation::Fishes.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::fish_bundle::Relation::Bundle.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
