//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "fish_bundle")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub fish_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub bundle_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::bundle::Entity",
        from = "Column::BundleId",
        to = "super::bundle::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Bundle,
    #[sea_orm(
        belongs_to = "super::fishes::Entity",
        from = "Column::FishId",
        to = "super::fishes::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Fishes,
}

impl Related<super::bundle::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Bundle.def()
    }
}

impl Related<super::fishes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Fishes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
