//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.4

pub mod prelude;

pub mod accounts;
pub mod bundle;
pub mod catches;
pub mod fish_bundle;
pub mod fishes;
pub mod messages;
pub mod sea_orm_active_enums;
pub mod season_data;
pub mod seasons;
pub mod users;
