//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "seasons")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub start: DateTimeWithTimeZone,
    pub end: Option<DateTimeWithTimeZone>,
    pub bundle_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::bundle::Entity",
        from = "Column::BundleId",
        to = "super::bundle::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Bundle,
    #[sea_orm(has_many = "super::catches::Entity")]
    Catches,
    #[sea_orm(has_many = "super::season_data::Entity")]
    SeasonData,
}

impl Related<super::bundle::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Bundle.def()
    }
}

impl Related<super::catches::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Catches.def()
    }
}

impl Related<super::season_data::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SeasonData.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
